# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade pip-tools
    pip-sync ubuntu64-py310-requirements.txt
  displayName: 'Install dependencies'

- script: |
    fab -l
  displayName: 'Running fab -l'

- script: |
    auth --help
  displayName: 'Running auth --help'

- script: |
    pylint fabfile
  displayName: 'Running pylint fabfile'

- script: |
    pylint python/plush
  displayName: 'Running pylint python/plush'
